import 'bootstrap/dist/css/bootstrap.css';
import './globals.scss'
import type { Metadata } from 'next'
import { Gideon_Roman } from 'next/font/google'
import icon from './icon.png'

const gideon_Roman = Gideon_Roman({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Conversor de Números Romanos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // necesito este useEffect si quiero utilizar códigos de javascript desde Bootstrap
  // useEffect(() => { 
  //   require('bootstrap/dist/js/bootstrap.bundle.min.js');
  // }, []);

  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href={icon.src} />
      </head>
      <body className={gideon_Roman.className}>{children}</body>
    </html>
  )
}
